Backport fix for ip link add name regression that broke libvirt
Used to work in 3.14, broken in 3.16. Fix already upstream.
Libvirt does this when adding a veth pair:

  # ip link add vnet18 type veth peer name vnet19
  Error: argument "vnet18" is wrong: Unknown device